version: '3.3'

services:
  php:
    container_name: yii-advanced
    build: ./docker/images/php
    links:
      - mysql
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
  mysql:
    container_name: yii2_sql
    image: mysql:5.7.34
    volumes:
      - ./docker/sql/:/var/lib/mysql
      - ./docker/config/mysql:/etc/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii
      - MYSQL_USER=yii
      - MYSQL_PASSWORD=yii